language: go

arch:
    - AMD64
    - ppc64le

go:
    - 1.13
    - 1.14
    - 1.15

script:
    - ./validate.sh

# this should give us faster builds according to 
# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
